#!/usr/bin/env node
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import {json,emit,event,requestModel,sha256} from './core.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const configPath=path.resolve(process.argv[2]),runDir=path.resolve(process.argv[3]),sourcePath=path.resolve(process.argv[4]);
const config=await json(configPath),chapter=await json(sourcePath);
const validate=new Ajv2020({allErrors:true}).compile(await json(path.join(root,'schemas/chapter-unit-candidate.schema.json')));
const parse=t=>{if(!t?.trim())throw new Error('EMPTY_MODEL_RESPONSE');const s=t.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]||t;return JSON.parse(s)};
const commonMission='Produce one independent FLT candidate under the same constitutional goal as every other candidate: communicate the full meaning, logic, tone, discourse movement, and theological force of the Greek in clear, natural, dignified English that a religion-naive adult can follow on one hearing. Build natural English sentences and paragraphs rather than preserving Greek clause architecture. Dynamic expression is the default; preserve material meaning and avoid unsupported commentary.';
async function call(worker,unit,prompt){let repair='';for(let attempt=1;attempt<=3;attempt++){const full=`Return complete JSON only. ${repair}\n${prompt}`,started=new Date(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),config.timeout_ms||180000);try{const r=await requestModel(worker,full,controller.signal);await emit(runDir,`failures/raw/${unit.unit_id}/${worker.role}/attempt-${attempt}.txt`,r.text);const output=parse(r.text);if(!validate(output)){repair=`Repair schema errors: ${JSON.stringify(validate.errors)}. Be concise.`;throw new Error(repair)}const refs=output.verse_renderings.map(v=>v.reference),expected=unit.verses.map(v=>v.reference);if(JSON.stringify(refs)!==JSON.stringify(expected)){repair=`Return exactly these verse references in order: ${expected.join(', ')}.`;throw new Error(repair)}const record={run_id:config.run_id,chapter_id:chapter.chapter_id,unit_id:unit.unit_id,stage:'blind_reader_first_unit_draft',role:worker.role,attempt,input_sha256:sha256(full),output,provider_provenance:{provider:worker.provider,model:worker.model,request_id:r.id,started_at:started.toISOString(),finished_at:new Date().toISOString(),usage:r.usage}};await event(runDir,{type:'unit_draft_complete',unit_id:unit.unit_id,role:worker.role,attempt});return record}catch(e){if(!repair)repair=`Previous response was incomplete or malformed: ${String(e)}. Close the JSON and be concise.`;await event(runDir,{type:'unit_draft_failure',unit_id:unit.unit_id,role:worker.role,attempt,error:String(e)});if(attempt===3)throw e}finally{clearTimeout(timer)}}}

const provenance=[];
for(const unit of chapter.units){
  const common={project:{translation_identity:chapter.translation_identity,target_reader:chapter.target_reader,tone:chapter.tone},governing_rules:chapter.governing_rules,existing_decisions:chapter.existing_decisions,matrix_entries:chapter.matrix_alerts||[],unit:{unit_id:unit.unit_id,passage:unit.passage,title:unit.title,known_issues:unit.known_issues,verses:unit.verses},visibility:{sealed_human_unit_absent:!chapter.sealed_unit,comparison_translations_absent:true,benchmark_absent:true}};
  const results=await Promise.all(config.workers.map(w=>call(w,unit,`You are drafting one blind unit for FLT ${chapter.book} ${chapter.chapter}. Mission: ${commonMission} The reading text is firmly dynamic-equivalence; closeness to Greek form is not a virtue by itself. Make the main assertion easy to hear; split, combine, reorder, or unpack when needed. Actively avoid stacked clauses, preposition clusters, delayed subjects or main verbs, abstract-noun chains, embedded explanations, repetitive English openings, and translated-sounding prose. Preserve deliberate repetition, escalation, logical relationships, meaningful ambiguity, agency, force, and key-term links. Do not self-certify oral quality: record the oral design moves you made and any remaining risk. Do not reconstruct or refer to any sealed human wording. Schema: {"verse_renderings":[{"reference":"${unit.verses[0].reference}","text":"..."}],"paragraph_rendering":"...","dynamic_moves":[{"reference":"...","move":"...","warrant":"..."}],"oral_design_moves":[{"reference":"...","obstacle":"...","move":"...","source_warrant":"..."}],"remaining_oral_risks":[{"reference":"...","risk":"..."}],"risks":[{"reference":"...","risk":"..."}],"human_questions":[{"reference":"...","question":"...","options":["...","..."]}]}. MATERIAL:${JSON.stringify(common)}`)));
  if(new Set(results.map(x=>x.input_sha256)).size!==1)throw new Error(`Common-prompt hash mismatch for ${unit.unit_id}`);
  for(const x of results){await emit(runDir,`outputs/units/${unit.unit_id}/${x.role}.json`,x);provenance.push(x)}
  let md=`# ${unit.passage} — Blind Reader-First Candidates\n\n**Status:** Human editing required; no candidate is approved.\n\n`;
  for(const [i,x] of results.entries())md+=`## Candidate ${String.fromCharCode(65+i)}\n\n${x.output.verse_renderings.map(v=>`**${v.reference.replace(/^Phil\.\d+\./,'')}** ${v.text}`).join('\n\n')}\n\n`;
  await emit(runDir,`outputs/briefs/${unit.unit_id}.md`,md);
}
await emit(runDir,'manifest/chapter-drafting-provenance.json',{run_id:config.run_id,chapter_id:chapter.chapter_id,sealed_unit:chapter.sealed_unit,common_prompt_sha256:provenance[0]?.input_sha256,common_prompt_verified:new Set(provenance.map(x=>x.input_sha256)).size===1,provider_calls:provenance.map(x=>x.provider_provenance),visibility:'Each worker saw one Greek unit, project rules, and scoped decisions. Any sealed human wording, benchmarks, and comparison translations were absent.',status:'remaining_units_ready_for_human_editing'});
console.log('Blind unit drafting complete');
